# Generated by Django 6.1 on 2026-08-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Secondary image displayed on hover', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('200ml', '200 ml'), ('500ml', '500 ml'), ('700ml', '700 ml'), ('750ml', '750 ml'), ('1L', '1 Litre')], default='700ml', max_length=10),
        ),
    ]
