# Generated by Django 6.1 on 2026-08-15 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_secondary_image_alter_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.order',),
        ),
    ]
